- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py36
        - ovsdbapp-tempest-dsvm-networking-ovn-ovs-release
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py36
        - ovsdbapp-tempest-dsvm-networking-ovn-ovs-release
